### PR TITLE
Add some fiture

### PR DESCRIPTION
**Pull request by rizki5411**
validate, delete, bug fix & more

### CODE REVIEW

**Comment by rizki5411** [comment]
Hacktoberfest, please give my PR with label hacktoberfest-accepted, thanks

**Comment by rizki5411** [comment]
Hello, pelase merged my PR & give me label hacktoberfest-accepted, thanks
#hacktoberfest

**Comment by rizki5411** [comment]
Hello @yyppsk please merge my PR dan add the label hacktoberfest-accepted

**Comment by rizki5411** [comment]
Please add label hacktoberfest-accepted @yyppsk

**Comment by yyppsk** [comment]
> Please add label hacktoberfest-accepted @yyppsk

Definitely!

**Review by yyppsk — COMMENTED** [review]
#hacktoberfest-accepted

**Pull request merged**
